name: ConnectServer tests

on: [push, pull_request]

jobs:
  test-CS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install ConnectServer dependencies
        run: |
          cd ConnectServer
          yarn

      - name: Run ConnectServer tests
        run: |
          cd ConnectServer
          yarn test
